### ISSUE TITLE
Specify the stateMachine ARN to environment variables

### ISSUE THREAD

**Issue by e-nouri** [horike37/serverless-step-functions#228]
# This is a (Bug Report / Feature Proposal)
Bug
## Description

I cannot get the ARN, I tried the exact same thing as the doc suggested, but it still not resolve.

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

## Additional Data
* ***Serverless Framework Core Version you're using***:
* ***The Plugin Version you're using***: 
  "devDependencies": {
    "serverless-offline-python": "^3.22.0",
    "serverless-pseudo-parameters": "^2.4.0",
    "serverless-python-requirements": "^4.3.0",
    "serverless-step-functions": "^2.0.0",
    "serverless-wsgi": "^1.7.2"
  }

* ***Operating System***: Mac OS Catalina
* ***Stack Trace***:

`Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [closeOrderDelayed] in the Resources block of the template
    at provider.request.catch (/Users/nourix2/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:24:13)
From previous event:
    at AwsDeploy.validateTemplate (/Users/nourix2/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:19:12)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/Users/nourix2/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:119:39)
From previous event:
    at Object.aws:deploy:deploy:validateTemplate [as hook] (/Users/nourix2/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:115:10)
    at BbPromise.reduce (/Users/nourix2/.nvm/versions/node/v8.12.0/lib/node_modules/serverless/lib/classes/PluginManager.js:446:55)`

* ***Provider Error messages***:
The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [closeOrderDelayed] in the Resources block of the template

* ***Serverless YAML***:
`
# you can add packaging information here
package:
  individually: true
  include:
    - services/**
  #  exclude:
  #    - exclude-me.py
  #    - exclude-me-dir/**

# Functions used for Lambda and API Gateway
functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
  inviteFriends:
    handler: services.friends.inviteFriends
  notifyUserApp:
    handler: services.friends.inviteFriends
  closeOrder:
    handler: services.order.closeOrder
    environment:
      STATE_MACHINE_ORDER: ${self:resources.Outputs.closeOrderDelayed.Value}

# Step functions used by Lambda#
stepFunctions:
  stateMachines:
    closeOrderDelayedFunc:
      name: closeOrderDelayed
      definition:
        Comment: "Close Order with a delay in seconds"
        StartAt: Delay
        States:
          Delay:
            Type: Wait
            SecondsPath: "$.delay_seconds"
            Next: Close
          Close:
            Type: Task
            Resource: "arn:aws:states:::lambda:invoke"
            Parameters:
              FunctionName:
                'Fn::ImportValue': closeOrder
              Payload:
                "Input.$": "$.lambda_payload"
            End: true

custom:
  pythonRequirements:
    usePipenv: false
    fileName: requirements.txt
    invalidateCaches: false
  wsgi:
    app: run.app

resources:
  Outputs:
    closeOrderDelayed:
      Value:
        Ref: closeOrderDelayed

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-step-functions
  - serverless-pseudo-parameters`

**Comment by theburningmonk** [comment]
@e-nouri you need to reference the logical ID, not the state machine name. See [here](https://github.com/horike37/serverless-step-functions#adding-a-custom-logical-id-for-a-statemachine).

**Comment by e-nouri** [comment]
@theburningmonk thank you Yan for your quick response, that fixed it but now I have problem with the generated IAM policy:

`An error occurred: IamRoleStateMachineExecution - Syntax errors in policy. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID`

Here is the full serverless yaml file (expet thee envs):
```

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
  inviteFriends:
    handler: services.friends.inviteFriends
  notifyUserApp:
    handler: services.friends.inviteFriends
  closeOrder:
    handler: services.order.closeOrder
    environment:
      STATE_MACHINE_ORDER: ${self:resources.Outputs.CloseOrderStateMachine.Value}

stepFunctions:
  stateMachines:
    closeOrderDelayedFunc:
      name: CloseOrder
      id: CloseOrderStateMachine
      dependsOn:
        - CloseOrderLambdaFunction
      definition:
        Comment: "Close Order with a delay in seconds"
        StartAt: Delay
        States:
          Delay:
            Type: Wait
            SecondsPath: "$.delay_seconds"
            Next: Close
          Close:
            Type: Task
            Resource: "arn:aws:states:::lambda:invoke"
            Parameters:
              FunctionName: ${self:resources.Outputs.CloseOrderLambda.Value}
              Payload:
                "Input.$": "$.lambda_payload"
            End: true

custom:
  pythonRequirements:
    usePipenv: false
    fileName: requirements.txt
    invalidateCaches: false
  wsgi:
    app: run.app


  Outputs:
    CloseOrderStateMachine:
      Value:
        Ref: CloseOrderStateMachine
    CloseOrderLambda:
      Value:
        Fn::GetAtt: [CloseOrderLambdaFunction, Arn]

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-step-functions
  - serverless-pseudo-parameters
```

my IAM statements are pretty simple:

```
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - lambda:InvokeFunction
      Resource: '*'
    - Effect: "Allow"
      Action:
        - states:StartExecution
      Resource: '*'
```
from the comments and the issue I saw that 1.6.1 fixed a similar bug, after reading the generated cloudformation json, i think the problem is related to the Policy for invoking lambdas from the state machine:

```
    "IamRoleStateMachineExecution": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "states.eu-west-1.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": "dev-eu-west-1-api-lemajordome-statemachine",
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "lambda:InvokeFunction"
                  ],
                  "Resource": [
                    {}
                  ]
                }
              ]
            }
          }
        ]
      }
    },
```

Also after more reading I noticied that the ARN from the Lambda to be invoked by the StateMachine is not correctly appended to the parameter of the definition of the SM:
```

    "CloseOrderStateMachine": {
      "Type": "AWS::StepFunctions::StateMachine",
      "Properties": {
        "DefinitionString": "{\n  \"Comment\": \"Close Order with a delay in seconds\",\n  \"StartAt\": \"Delay\",\n  \"States\": {\n    \"Delay\": {\n      \"Type\": \"Wait\",\n      \"SecondsPath\": \"$.delay_seconds\",\n      \"Next\": \"Close\"\n    },\n    \"Close\": {\n      \"Type\": \"Task\",\n      \"Resource\": \"arn:aws:states:::lambda:invoke\",\n      \"Parameters\": {\n        \"FunctionName\": {},\n        \"Payload\": {\n          \"Input.$\": \"$.lambda_payload\"\n        }\n      },\n      \"End\": true\n    }\n  }\n}",
        "RoleArn": {
          "Fn::GetAtt": [
            "IamRoleStateMachineExecution",
            "Arn"
          ]
        },
        "Tags": [],
        "StateMachineName": "CloseOrder"
      },
      "DependsOn": [
        "IamRoleStateMachineExecution",
        "CloseOrderLambdaFunction"
      ]
    },
```

**Comment by e-nouri** [comment]
I saw that the version 2.0.1 is ut, so I tried it, I think ti fixes the problem but there is another one with n::Sub for the definition:

`The CloudFormation template is invalid: Template error: every value of the context object of every Fn::Sub object must be a string or a function that returns a string`

```
    "CloseOrderStateMachine": {
      "Type": "AWS::StepFunctions::StateMachine",
      "Properties": {
        "DefinitionString": {
          "Fn::Sub": [
            "{\n  \"Comment\": \"Close Order with a delay in seconds\",\n  \"StartAt\": \"Delay\",\n  \"States\": {\n    \"Delay\": {\n      \"Type\": \"Wait\",\n      \"SecondsPath\": \"$.delay_seconds\",\n      \"Next\": \"Close\"\n    },\n    \"Close\": {\n      \"Type\": \"Task\",\n      \"Resource\": \"${RlfQmjSNDH}\",\n      \"End\": true\n    }\n  }\n}",
            {
              "RlfQmjSNDH": {
                "Fn::GetAtt": [
                  "CloseOrderLambdaFunction",
                  "Arn"
                ],
                "Input.$": "$.lambda_payload"
              }
            }
          ]
        },
        "RoleArn": {
          "Fn::GetAtt": [
            "IamRoleStateMachineExecution",
            "Arn"
          ]
        },
        "Tags": [],
        "StateMachineName": "CloseOrder"
      },
      "DependsOn": [
        "IamRoleStateMachineExecution",
        "CloseOrderLambdaFunction"
      ]
    },
```

**Comment by theburningmonk** [comment]
instead of:
```
Close:
  Type: Task
  Resource: "arn:aws:states:::lambda:invoke"
  Parameters:
    FunctionName: ${self:resources.Outputs.CloseOrderLambda.Value}
    Payload:
      "Input.$": "$.lambda_payload"
    End: true
```

try `Ref` the function directly? i.e.

```
Close:
  Type: Task
  Resource: "arn:aws:states:::lambda:invoke"
  Parameters:
    FunctionName:
      Fn::GetAtt: [CloseOrderLambdaFunction, Arn]
    Payload:
      "Input.$": "$.lambda_payload"
    End: true
```

I think that should fix the problem.

**Comment by e-nouri** [comment]
Did not work:
`An error occurred: CloseOrderLambdaFunction - Value of property Variables must be an object with String (or simple type) properties.`

**Comment by theburningmonk** [comment]
mm.. not sure what's going on there. I just put together a new project, and here's my `serverless.yml`

```
service: sfn-test

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs10.x

functions:
  closeOrder:
    handler: handler.hello

stepFunctions:
  stateMachines:
    closeOrderDelayedFunc:
      name: CloseOrder
      id: CloseOrderStateMachine
      dependsOn:
        - CloseOrderLambdaFunction
      definition:
        Comment: "Close Order with a delay in seconds"
        StartAt: Delay
        States:
          Delay:
            Type: Wait
            SecondsPath: "$.delay_seconds"
            Next: Close
          Close:
            Type: Task
            Resource: "arn:aws:states:::lambda:invoke"
            Parameters:
              FunctionName:
                Fn::GetAtt: [CloseOrderLambdaFunction, Arn]
              Payload:
                "Input.$": "$.lambda_payload"
            End: true

resources:
  Outputs:
    CloseOrderStateMachine:
      Value:
        Ref: CloseOrderStateMachine
    CloseOrderLambda:
      Value:
        Fn::GetAtt: [CloseOrderLambdaFunction, Arn]
```

and I'm able to deploy it just fine. It's possible that the other plugins you have doesn't play well with serverless-step-functions, can you try removing them and see if you still get the same error?

**Comment by e-nouri** [comment]
I made a fresh serverless service, added the step functions plugin and deployed it, it excuted correctly without any error, but I did not find any state machine on my aws console ! may be I am missing something here ?! here is the link to the test project i did: https://github.com/e-nouri/serverless-state-machine.

For my actual project still the same problem, it stoppes after the "Checking Stack update progress", here is the outputted error:
`An error occurred: CloseOrderLambdaFunction - Value of property Variables must be an object with String (or simple type) properties.`

**Comment by theburningmonk** [comment]
haha, that doesn't sound right! the template looks fine, did you check you are in the right region? was the state machine in the CloudFormation template at all?

It sounds like the error in your actual project is related to the closeOrder function itself: https://forum.serverless.com/t/value-of-property-variables-must-be-an-object/1372/3

**Comment by e-nouri** [comment]
Yes I checked the region, and I added "region: eu-west-1" to be sure and redeploy, I have the lambda but I don't see any state machine on my console.

**Comment by theburningmonk** [comment]
In this file https://github.com/e-nouri/serverless-state-machine/blob/master/serverless.yml you didn't have a region so it'll have been deployed to us-east-1.

If you look at the output from the SLS framework deploy, you should see the region also.

**Comment by e-nouri** [comment]
I fixed it ,my bad I got mixed, now it is working fine and it gets the proper Lambda ARN. I think the problem is with the serverless-wsgi and step-functions together.

**Comment by e-nouri** [comment]
I found the problem, i made a fresh python-aws, deployed it, worked for both sm and lambda, as soon as I add this line it stops working 
```
functions:
  hello:
    handler: handler.hello
    environment:
      STATE_MACHINE_ORDER: ${self:resources.Outputs.CloseOrderStateMachine.Value}
```

Without the     `environment: STATE_MACHINE_ORDER: ${self:resources.Outputs.CloseOrderStateMachine.Value}` it works fine, but if i added I have this error: 

`An error occurred: HelloLambdaFunction - Value of property Variables must be an object with String (or simple type) properties.`

This is a full serverless file:


```
service: test-sm # NOTE: update this with your service name
#app: your-app-name
#tenant: your-tenant-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python2.7
  region: eu-west-1
  profile: nourix2

functions:
  hello:
    handler: handler.hello
    environment:
      STATE_MACHINE_ORDER: ${self:resources.Outputs.CloseOrderStateMachine.Value}

stepFunctions:
  stateMachines:
    closeOrderDelayedFunc:
      dependsOn: HelloLambdaFunction
      name: CloseOrder
      id: CloseOrderStateMachine
      definition:
        Comment: "Close Order with a delay in seconds"
        StartAt: Delay
        States:
          Delay:
            Type: Wait
            SecondsPath: "$.delay_seconds"
            Next: Close
          Close:
            Type: Task
            Resource: "arn:aws:states:::lambda:invoke"
            Parameters:
              FunctionName:
                Fn::GetAtt: [HelloLambdaFunction, Arn]
              Payload:
                "Input.$": "$.lambda_payload"
            End: true

Outputs:
  CloseOrderStateMachine:
    Value:
      Ref: CloseOrderStateMachine

plugins:
  - serverless-step-functions
```

**Comment by theburningmonk** [comment]
and what if you use `Ref` in the environment directly? i.e.

```
functions:
  hello:
    handler: handler.hello
    environment:
      STATE_MACHINE_ORDER:
        Ref: CloseOrderStateMachine
```

in fact, since you're naming the state machine explicitly - i.e. `CloseOrder` in this case - why not just do this:

```
functions:
  hello:
    handler: handler.hello
    environment:
      STATE_MACHINE_ORDER: CloseOrder
```

**Comment by e-nouri** [comment]
I tried that, that will generate a circular dependency:
`The CloudFormation template is invalid: Circular dependency between resources: [HelloLambdaFunction, IamRoleStateMachineExecution, HelloLambdaVersionFgRW4z5kZgBNNqxXnODogelHt34IDxLCVr1qjKPZyg, CloseOrderStateMachine]`

**Comment by e-nouri** [comment]
I think the solution is to make a custom IAM rule and add it to both the lambda and the state machine, because they both have direct links to each other, but what i am not sure about is the output is supposd to be resolved as the last one, by that i mean lambda gets created first => state machine => outputs => assign the output value back to the lambda, but that does not seem to be the case, because even with the output, it generates a circular dependency !

**Comment by e-nouri** [comment]
This is another workaround what works with pseudo-parameters, but I couldn't get the name of the step function to resolve dynamically so i hardcoded it, but it works, if you know how it will make this solution much better. I think there is an actually bug, not related to any other plugin, just with the step-functions.

BTW, thank you so much for your help.

```
service: test-sm # NOTE: update this with your service name
#app: your-app-name
#tenant: your-tenant-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python2.7
  region: eu-west-1
  profile: nourix2

functions:
  hello:
    handler: handler.hello
    environment:
      STATE_MACHINE_ORDER: "arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:CloseOrder"

stepFunctions:
  stateMachines:
    closeOrderDelayedFunc:
      name: CloseOrder
      id: CloseOrderStateMachine
      definition:
        Comment: "Close Order with a delay in seconds"
        StartAt: Delay
        States:
          Delay:
            Type: Wait
            SecondsPath: "$.delay_seconds"
            Next: Close
          Close:
            Type: Task
            Resource: "arn:aws:states:::lambda:invoke"
            Parameters:
              FunctionName:
                Fn::GetAtt: [HelloLambdaFunction, Arn]
              Payload:
                "Input.$": "$.lambda_payload"
            End: true

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

resources:
  Outputs:
    CloseOrderStateMachine:
      Value:
        Ref: CloseOrderStateMachine
```

**Comment by theburningmonk** [comment]
Ha, I didn't realise the state machine calls the function that starts the state machine. That's a bit unusual, wouldn't you end up with an infinite recursion in that case?

**Comment by e-nouri** [comment]
sorry for the delayed response, no it is not a recursion, some of the use cases you want to trigger a lambda in the future, this future can be near or far, the best solution that i found is step functions (at least for the near future, 15/20 min), that's why i have the configurable delay with the lambda behind it. Thanks for you help Yan, 非常感谢师傅。
